import { beforeEach, describe, expect, it, vi } from "vitest";
import { FILE_UPLOAD_STATUS } from "@/lib/file/file-upload-status";

/**
 * Regression tests for library auto-metadata.
 *
 * The user-visible feature is "an uploaded file gets renamed and described
 * based on what the LLM found inside it". That only happens if
 * SyncQueueService.processFileUpload takes the generated metadata off the RAG
 * result and persists it to file_metadata. The unit tests in
 * library-metadata-service.test.ts prove the LLM call is well formed; these
 * prove the result actually reaches the library.
 */

const mockFileDAOInstance = {
	getFileForRag: vi.fn(),
	updateFileMetadata: vi.fn().mockResolvedValue(undefined),
	updateFileRecord: vi.fn().mockResolvedValue(undefined),
	updateFileRecordWithError: vi.fn().mockResolvedValue(undefined),
	addToSyncQueue: vi.fn().mockResolvedValue(undefined),
	displayNameExistsForUser: vi.fn().mockResolvedValue(false),
};

vi.mock("@/dao", () => {
	// biome-ignore lint/complexity/useArrowFunction: arrow cannot be used with `new` in Vitest 4
	const FileDAO = vi.fn().mockImplementation(function () {
		return mockFileDAOInstance;
	}) as any;
	FileDAO.STATUS = FILE_UPLOAD_STATUS;
	return { FileDAO };
});

const mockRagInstance = {
	shouldQueueFile: vi.fn().mockResolvedValue({ shouldQueue: false }),
	processFile: vi.fn(),
};

vi.mock("@/services/rag/rag-service", () => ({
	// biome-ignore lint/complexity/useArrowFunction: arrow cannot be used with `new` in Vitest 4
	LibraryRAGService: vi.fn().mockImplementation(function () {
		return mockRagInstance;
	}),
}));

const notifyMetadataAutoGenerated = vi.fn().mockResolvedValue(undefined);
vi.mock("@/lib/notifications", () => ({
	notifyMetadataAutoGenerated: (...args: unknown[]) =>
		notifyMetadataAutoGenerated(...args),
	notifyFileIndexingStatus: vi.fn().mockResolvedValue(undefined),
}));

vi.mock("@/services/campaign/library-entity-discovery-queue-service", () => ({
	LibraryEntityDiscoveryQueueService: {
		queueDiscoveryAfterIndexing: vi.fn().mockResolvedValue(undefined),
	},
}));

vi.mock("@/dao/telemetry-dao", () => ({
	// biome-ignore lint/complexity/useArrowFunction: arrow cannot be used with `new` in Vitest 4
	TelemetryDAO: vi.fn().mockImplementation(function () {
		return {};
	}),
}));

vi.mock("@/services/telemetry/telemetry-service", () => ({
	// biome-ignore lint/complexity/useArrowFunction: arrow cannot be used with `new` in Vitest 4
	TelemetryService: vi.fn().mockImplementation(function () {
		return {
			recordFileProcessingDuration: vi.fn().mockResolvedValue(undefined),
		};
	}),
}));

import { SyncQueueService } from "@/services/file/sync-queue-service";

const FILE_KEY = "uploads/user-123/players-handbook_v3.2_FINAL.pdf";
const FILE_NAME = "players-handbook_v3.2_FINAL.pdf";
const USERNAME = "user-123";

const mockEnv = () =>
	({
		DB: {},
		R2: {
			get: vi.fn().mockResolvedValue({ size: 1024, httpMetadata: {} }),
		},
	}) as any;

/** A file row as inserted by upload: no display_name, empty description. */
const freshDbRow = (overrides: Record<string, unknown> = {}) => ({
	file_key: FILE_KEY,
	username: USERNAME,
	file_name: FILE_NAME,
	file_size: 1024,
	content_type: "application/pdf",
	display_name: null,
	description: "",
	tags: "[]",
	status: "uploaded",
	created_at: "2026-01-01T00:00:00Z",
	updated_at: "2026-01-01T00:00:00Z",
	...overrides,
});

const generatedResult = (overrides: Record<string, unknown> = {}) => ({
	displayName: "Player's Handbook",
	description: "Core rulebook covering character creation and combat rules.",
	tags: ["rules", "core"],
	vectorId: "vec-1",
	...overrides,
});

describe("SyncQueueService.processFileUpload — auto-generated metadata", () => {
	beforeEach(() => {
		vi.clearAllMocks();
		mockFileDAOInstance.getFileForRag.mockResolvedValue(freshDbRow());
		mockFileDAOInstance.displayNameExistsForUser.mockResolvedValue(false);
		mockRagInstance.shouldQueueFile.mockResolvedValue({ shouldQueue: false });
		mockRagInstance.processFile.mockResolvedValue(generatedResult());
	});

	it("persists the LLM-generated display name and description", async () => {
		const result = await SyncQueueService.processFileUpload(
			mockEnv(),
			USERNAME,
			FILE_KEY,
			FILE_NAME
		);

		expect(result.success).toBe(true);
		expect(mockFileDAOInstance.updateFileMetadata).toHaveBeenCalledTimes(1);

		const [fileKey, updates] =
			mockFileDAOInstance.updateFileMetadata.mock.calls[0];
		expect(fileKey).toBe(FILE_KEY);
		expect(updates.display_name).toBe("Player's Handbook");
		expect(updates.description).toBe(
			"Core rulebook covering character creation and combat rules."
		);
		expect(JSON.parse(updates.tags)).toEqual(["rules", "core"]);
	});

	it("notifies the user that metadata was auto-generated", async () => {
		await SyncQueueService.processFileUpload(
			mockEnv(),
			USERNAME,
			FILE_KEY,
			FILE_NAME
		);

		expect(notifyMetadataAutoGenerated).toHaveBeenCalledTimes(1);
		const [, , , payload] = notifyMetadataAutoGenerated.mock.calls[0] as any[];
		expect(payload.displayName).toBe("Player's Handbook");
		expect(payload.description).toContain("Core rulebook");
	});

	it("de-duplicates a display name that collides with an existing file", async () => {
		mockFileDAOInstance.displayNameExistsForUser
			.mockResolvedValueOnce(true)
			.mockResolvedValue(false);

		await SyncQueueService.processFileUpload(
			mockEnv(),
			USERNAME,
			FILE_KEY,
			FILE_NAME
		);

		const [, updates] = mockFileDAOInstance.updateFileMetadata.mock.calls[0];
		expect(updates.display_name).not.toBe("Player's Handbook");
		expect(updates.display_name).toContain("Player's Handbook");
	});

	it("does not overwrite a display name the user already set", async () => {
		mockFileDAOInstance.getFileForRag.mockResolvedValue(
			freshDbRow({ display_name: "My Own Name" })
		);

		await SyncQueueService.processFileUpload(
			mockEnv(),
			USERNAME,
			FILE_KEY,
			FILE_NAME
		);

		const [, updates] = mockFileDAOInstance.updateFileMetadata.mock.calls[0];
		expect(updates.display_name).toBeUndefined();
		expect(updates.description).toBe(
			"Core rulebook covering character creation and combat rules."
		);
	});

	it("does not overwrite a description the user already set", async () => {
		mockFileDAOInstance.getFileForRag.mockResolvedValue(
			freshDbRow({ description: "My own description" })
		);

		await SyncQueueService.processFileUpload(
			mockEnv(),
			USERNAME,
			FILE_KEY,
			FILE_NAME
		);

		const [, updates] = mockFileDAOInstance.updateFileMetadata.mock.calls[0];
		expect(updates.description).toBeUndefined();
		expect(updates.display_name).toBe("Player's Handbook");
	});

	it("does not overwrite tags the user already set", async () => {
		mockFileDAOInstance.getFileForRag.mockResolvedValue(
			freshDbRow({ tags: JSON.stringify(["mine"]) })
		);

		await SyncQueueService.processFileUpload(
			mockEnv(),
			USERNAME,
			FILE_KEY,
			FILE_NAME
		);

		const [, updates] = mockFileDAOInstance.updateFileMetadata.mock.calls[0];
		expect(updates.tags).toBeUndefined();
	});

	// When generation fails the service returns no displayName/description.
	// Nothing should be written — in particular the filename must not be
	// laundered into display_name, which is what made the outage invisible.
	it("writes nothing when the model produced no metadata", async () => {
		mockRagInstance.processFile.mockResolvedValue(
			generatedResult({
				displayName: undefined,
				description: "",
				tags: [],
			})
		);

		const result = await SyncQueueService.processFileUpload(
			mockEnv(),
			USERNAME,
			FILE_KEY,
			FILE_NAME
		);

		expect(result.success).toBe(true);
		expect(mockFileDAOInstance.updateFileMetadata).not.toHaveBeenCalled();
		expect(notifyMetadataAutoGenerated).not.toHaveBeenCalled();
	});

	it("marks the file completed after saving metadata", async () => {
		await SyncQueueService.processFileUpload(
			mockEnv(),
			USERNAME,
			FILE_KEY,
			FILE_NAME
		);

		expect(mockFileDAOInstance.updateFileRecord).toHaveBeenCalledWith(
			FILE_KEY,
			FILE_UPLOAD_STATUS.COMPLETED
		);
	});
});
