/// <reference types="vitest/config" />
import path from "node:path";
import { defineConfig } from "vite";

export default defineConfig({
	resolve: {
		alias: {
			"@": path.resolve(__dirname, "./src"),
		},
	},
	test: {
		exclude: ["**/node_modules/**", "**/.claude/**", "**/tests/e2e/**"],
		testTimeout: 30000, // 30 second timeout per test
		hookTimeout: 30000, // 30 second timeout for hooks
		setupFiles: ["./tests/setup.ts"],
		globals: true,
		clearMocks: true,
		// Use threads pool instead of workers pool for all tests
		// Most tests mock the Workers environment and don't need the actual workerd runtime
		// This prevents port exhaustion from creating 46+ isolated workerd runtimes
		pool: "threads",
		coverage: {
			provider: "v8",
			reporter: ["text", "lcov", "html"],
			include: ["src/lib/**", "src/hooks/**", "src/routes/**", "src/tools/**"],
			exclude: [
				// Test files and config – never instrument
				"**/*.test.{ts,tsx}",
				"**/*.spec.{ts,tsx}",
				"**/tests/**",
				"**/*.d.ts",
				"**/vitest.config.ts",
				// Main app – large React root, better suited for e2e/integration tests
				"**/app.tsx",
				// Prompt templates – static strings for LLMs, no testable logic
				"**/lib/prompts/**",
				// Heavy external deps (Workers bindings, D1, R2, Durable Objects)
				"**/lib/agent-router.ts",
				"**/lib/agent-registry.ts",
				"**/lib/service-factory.ts",
				"**/lib/r2.ts",
				"**/lib/middleware.ts",
				"**/lib/durable-object-helpers.ts",
				// Env/secrets – needs Workers runtime or process.env
				"**/lib/env-utils.ts",
				// Config / constants – little or no executable logic
				"**/lib/model-manager.ts",
				"**/lib/model-config.ts",
				"**/lib/help-content.ts",
				"**/lib/rebuild-config.ts",
				"**/lib/importance-config.ts",
				"**/lib/agent-status-messages.ts",
				"**/lib/feature-flags.ts",
				"**/lib/feature-flags-react.ts",
				"**/lib/campaign-planning-checklist.ts",
				"**/lib/db-utils.ts",
				"**/lib/api/cors.ts",
				"**/lib/tool-auth.ts",
				"**/lib/auth-utils.ts",
				"**/lib/proposal-security.ts",
				"**/lib/event-bus.ts",
				"**/lib/stream-status-interceptor.ts",
				"**/lib/notifications.ts",
				"**/lib/notifications-rebuild.ts",
				"**/lib/campaign-operations.ts",
				"**/lib/ai-search-utils.ts",
				"**/lib/route-utils.ts",
				"**/lib/entity/entity-secured-fields.ts",
				"**/lib/errors.ts",
				"**/lib/logger.ts",
				"**/routes/**",
				// Hooks – integration-heavy, need full app context
				"**/hooks/useActivityTracking.ts",
				"**/hooks/useAppAuthentication.ts",
				"**/hooks/useAppEventHandlers.ts",
				"**/hooks/useAppState.ts",
				"**/hooks/useAuthenticatedRequest.ts",
				"**/hooks/useBillingStatus.ts",
				"**/hooks/useCampaignAddition.ts",
				"**/hooks/useCampaignManagement.ts",
				"**/hooks/useCampaignRebuildStatuses.ts",
				"**/hooks/useCampaigns.ts",
				"**/hooks/useFileUpload.ts",
				"**/hooks/useGlobalShardManager.ts",
				"**/hooks/useGraphVisualization.ts",
				"**/hooks/useNotificationStream.ts",
				"**/hooks/useLocalNotifications.ts",
				"**/hooks/usePlanningTasks.ts",
				"**/hooks/useProcessingProgress.ts",
				"**/hooks/useRebuildStatus.ts",
				"**/hooks/useResourceFileEvents.ts",
				"**/hooks/useRetryLimitStatus.ts",
				"**/hooks/useSessionDigests.ts",
				"**/hooks/useShardRenderGate.ts",
				"**/hooks/useTelemetryMetrics.ts",
				"**/hooks/useMenuNavigation.tsx",
				"**/hooks/useClickOutside.tsx",
				"**/hooks/useResourceFiles.ts",
				"**/hooks/useAuthReady.ts",
				"**/hooks/useChatSession.ts",
				"**/hooks/useAppOrchestration.ts",
				"**/hooks/useAsyncState.ts",
				"**/hooks/useTourState.tsx",
				"**/hooks/useActionQueueRetry.ts",
				"**/hooks/useUploadQueueRetry.ts",
				// Lib files requiring Workers/D1/full runtime
				"**/lib/agent-role-utils.ts",
				"**/lib/shard-factory.ts",
				"**/lib/graph/**",
				"**/lib/entity/entity-types.ts",
				// Tools requiring full LLM/DAO/Workers runtime – integration tested
				"**/tools/**/ai-helpers.ts",
				"**/tools/**/character-rules-fetcher.ts",
				"**/tools/**/assessment-core.ts",
				"**/tools/**/assessment-tools.ts",
				"**/tools/**/suggestion-tools.ts",
				"**/tools/**/suggestion-tools-helper.ts",
				"**/tools/campaign/plan-session-tool.ts",
				"**/tools/campaign/core-tools.ts",
				"**/tools/campaign/file-tools.ts",
				"**/tools/campaign/narrative-hooks-tool.ts",
				"**/tools/campaign/resource-tools.ts",
				"**/tools/campaign/readiness-tool.ts",
				"**/tools/campaign/planning-tools.ts",
				"**/tools/campaign/check-planning-readiness-tool.ts",
				"**/tools/campaign/generate-session-hooks-tool.ts",
				"**/tools/campaign/index.ts",
				"**/tools/campaign/planning/**",
				"**/tools/campaign/tools-utils.ts",
				"**/tools/campaign-context/character-tools.ts",
				"**/tools/campaign-context/checklist-tools.ts",
				"**/tools/campaign-context/community-tools.ts",
				"**/tools/campaign-context/creature-tools.ts",
				"**/tools/campaign-context/planning-context-tool.ts",
				"**/tools/campaign-context/loot-reward-tools.ts",
				"**/tools/campaign-context/planning-task-tools.ts",
				"**/tools/campaign-context/entity-tools.ts",
				"**/tools/campaign-context/search-tools.ts",
				"**/tools/campaign-context/recap-tools.ts",
				"**/tools/campaign-context/world-state-tools.ts",
				"**/tools/campaign-context/timeline-tools.ts",
				"**/tools/campaign-context/context-capture-tools.ts",
				"**/tools/campaign-context/get-document-content-tool.ts",
				"**/tools/campaign-context/rules-tools-helper.ts",
				"**/tools/campaign-context/index.ts",
				"**/tools/character-sheet/**",
				"**/tools/common/support-tools.ts",
				"**/tools/file/**",
				"**/tools/general/**",
				"**/tools/onboarding/**",
				"**/tools/session-digest/**",
				"**/tools/discovery-tools.ts",
				"**/tools/index.ts",
				"**/tools/message-history-tools.ts",
				"**/tools/utils.ts",
				// lib/file – exclude only Workers/large-file deps; file-utils, file-upload-security,
				// processing-time-estimator, text-chunking-utils are covered
				"**/lib/file/pdf-utils.ts",
				"**/lib/file/large-file-upload-helper.ts",
				"**/lib/file/split.ts",
			],
			thresholds: {
				lines: 75,
				functions: 75,
				branches: 70,
				"src/hooks/**": {
					lines: 75,
					functions: 75,
					branches: 75,
				},
				"src/routes/**": {
					lines: 75,
					functions: 75,
					branches: 75,
				},
				"src/tools/**": {
					lines: 75,
					functions: 75,
					branches: 60,
				},
			},
		},
	},
});
